--- #YAML:1.0
name:                Net-GPSD3-POE
version:             0.17
abstract:            Net::GPSD3 POE Session object
license:             ~
author:              
    - Michael R. Davis (domain=>michaelrdavis,tld=>com,account=>perl)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Net::GPSD3:                    0.17
    POE:                           0
    POE::Filter::Line:             0
    POE::Kernel:                   0
    POE::Session:                  0
    POE::Wheel::ReadWrite:         0
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
